"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import ez_setup
ez_setup.use_setuptools()

from setuptools import setup

APP = ['youtube.py']
DATA_FILES = ['config.json', 'playlist.json', 'youtube-dl', 'ffmpeg', 'youtube-dl.exe', 'ffmpeg.exe']
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
